apiVersion: apps/v1
kind: Deployment
metadata:
  name: homeassistant
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: homeassistant
  template:
    metadata:
      labels:
        app: homeassistant
    spec:
      containers:
      - image: ghcr.io/home-assistant/raspberrypi4-64-homeassistant:2022.3.1
        name: homeassistant
        ports:
        - containerPort: 8123
