kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: read-has
  namespace: application-service
subjects:
  - kind: User
    name: johnmcollier
  - kind: User
    name: sbose78
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
